version: "3.8"

services:
  web:
    build: .
    image: myapp:local
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
