services:
  web:
    image: YOUR_DOCKERHUB_USER/YOUR_REPO:latest   # thay bằng secrets DOCKERHUB_REPO
    container_name: myapp-web
    ports:
      - "8080:5000"
    restart: always
    environment:
      - PORT=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
