version: '3.8'
services:
web:
image: ${DOCKERHUB_REPO:-yourname/myapp}:latest
container_name: myapp-web
ports:
- "8080:86"
environment:
- ASPNETCORE_ENVIRONMENT=Production
restart: always
healthcheck:
test: ["CMD", "wget", "-qO-", "http://localhost:86/health"]
interval: 30s
timeout: 10s
retries: 3