version: '3.8'
services:
web:
image: ${DOCKERHUB_REPO:-yourname/myapp}:latest
container_name: myapp-web
ports:
- "8080:3000"
environment:
- NODE_ENV=production
restart: always
healthcheck:
test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
interval: 30s
timeout: 10s
retries: 3